spring.application.name=emailwriter

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.api.key=AIzaSyBBRF_CbVW2T1F1NAvnna9vIozQFDO0hB4
