spring.application.name=emailwriter

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.api.key=AIzaSyBLcm-grtDv0QIbhCp7_BwNJrIGXTBVO14

